Adding DOM Event Subscriptions to Components
actimeller/react-underhood-boilerplate pull request #3
Opened 2020-03-23 19:53 UTC by actimeller

2020-03-25 13:17 UTC, oceandrama requested changes

2020-03-25 13:17 UTC, oceandrama commented on samples/App.jsx
> +            onKeyUp={event => {
Я бы использовал колбэк `onChange`

2020-03-25 13:17 UTC, oceandrama commented on samples/App.jsx
> +            onKeyUp={event => {
И тебе нет смысла создавать здесь функцию, ты можешь просто указать `onChange={this.onInputChange}`

2020-03-25 13:17 UTC, oceandrama commented on samples/App.jsx
> +            onClick={() => {
Здесь то же самое. Просто передай функцию

2020-03-25 13:17 UTC, oceandrama commented on tests/App.test.js
> +      ],
Повторюсь, мне кажется, этот тест не имеет смысла. Ты сам в компоненте создал этот стейт, там даже функции никакие не вызываются. А тут ты, по сути, просто скопировал код из компонента

2020-03-25 13:17 UTC, oceandrama commented on tests/App.test.js
> +test("sortAlphabetByString works", () => {
Этот тест лучше сохранить в другом файле

2020-03-25 14:00 UTC, actimeller commented on samples/App.jsx
> +            onKeyUp={event => {
onChange не срабатывает, не знаю почему 
Стрелочная функция нужна для того чтобы не создавать контекст this. Без нее ошибка: 
```
App.jsx:21 Uncaught TypeError: this.setState is not a function
```

2020-03-25 14:01 UTC, actimeller commented on tests/App.test.js
> +      ],
Значит я совсем не понимаю, как нужно тестировать компоненты. Нужны пояснения.

2020-03-25 14:02 UTC, actimeller commented on tests/App.test.js
> +test("sortAlphabetByString works", () => {
В каком? Для каждого теста нужно создавать отдельный файл?

2020-03-25 14:56 UTC, oceandrama commented on samples/App.jsx
> +            onKeyUp={event => {
А, ну да, Реакт модифицирует его, стандартный  `onChange` срабатывает только при потере фокуса. Тогда `onInput`. Можешь сравнить его поведение с `keyUp` зажав какую-нибудь клавишу

2020-03-25 14:56 UTC, oceandrama commented on samples/App.jsx
> +            onKeyUp={event => {
Ты можешь сам `handleInputChange` сделать стрелочной функцией, тогда ошибки не будет

2020-03-25 14:56 UTC, oceandrama commented on tests/App.test.js
> +test("sortAlphabetByString works", () => {
Для тестирования каждого модуля нужен отдельный файл

2020-03-28 17:36 UTC, actimeller commented on samples/App.jsx
> +            onKeyUp={event => {
++

2020-03-28 17:37 UTC, actimeller commented on samples/App.jsx
> +            onClick={() => {
++

2020-03-28 17:37 UTC, actimeller commented on tests/App.test.js
> +test("sortAlphabetByString works", () => {
++

2020-03-30 18:04 UTC, oceandrama requested changes

2020-03-30 18:04 UTC, oceandrama commented on samples/App.jsx
> +            this.tick();
Это тоже можно забаиндить

2020-03-30 18:04 UTC, oceandrama commented on tests/App.test.jsx
> +test("Components works", () => {
Это лучше превратить в `describe`

2020-03-30 18:04 UTC, oceandrama commented on tests/App.test.jsx
> +  expect(DOM).toEqual({
А каждый `expect` в `test`

2020-03-30 18:04 UTC, oceandrama commented on tests/App.test.jsx
> +  expect(new ClassComponent()).toEqual({
Я бы здесь так же вызвал `render` и проверил результат

2020-03-30 18:04 UTC, oceandrama commented on tests/App.test.jsx
> +      children: [
Хм, выглядит странно, как будто при рендере это не отработает корректно

2020-03-30 18:04 UTC, oceandrama commented on utils/sortAlphabetByString.js
> +    .filter(symbol => alphabet.indexOf(symbol) >= 0);
Лучше использовать либо `!== -1` либо `includes`

2020-03-30 18:04 UTC, oceandrama commented on tests/sortAlphabetByString.test.js
> +});
А этот тест проходит?
```
sortAlphabetByString("абвгдеёжзийклмнопрстуфхцч".split(""), "хни")
```

2020-04-02 15:59 UTC, actimeller commented on utils/sortAlphabetByString.js
> +    .filter(symbol => alphabet.indexOf(symbol) >= 0);
++

2020-04-02 15:59 UTC, actimeller commented on tests/App.test.jsx
> +      children: [
Что делать?

2020-04-02 15:59 UTC, actimeller commented on tests/sortAlphabetByString.test.js
> +});
исправил функци, добавил тест

2020-04-02 15:59 UTC, actimeller commented on tests/App.test.jsx
> +  expect(new ClassComponent()).toEqual({
++

2020-04-02 15:59 UTC, actimeller commented on tests/App.test.jsx
> +  expect(DOM).toEqual({
мне кажется, что ++

2020-04-02 15:59 UTC, actimeller commented on tests/App.test.jsx
> +test("Components works", () => {
++

2020-04-02 15:59 UTC, actimeller commented on samples/App.jsx
> +            this.tick();
++

2020-04-03 12:57 UTC, actimeller commented on tests/App.test.jsx
> +      children: [
++

2020-04-03 18:35 UTC, oceandrama approved these changes

2020-04-05 17:18 UTC, merged