Встроенный профилировщик для нахождения наиболее проблемного места
actimeller/react-underhood-boilerplate pull request #4
Opened 2020-04-13 19:05 UTC by actimeller

Проверить работу имеющегося приложения с помощью полученного профилировщика, указать наиболее слабые места

Судя по работе профилировщика есть смысл сделать поверхностное сравнение объектов перед ререндером DOM объекта симулируя поведение ShouldComponentUpdate

2020-04-16 15:17 UTC, oceandrama commented on src/reconcile.js
> +    !element.type.isClass
А что за кейс тут появился? Как обновлять классовые компоненты?

2020-04-16 15:17 UTC, oceandrama commented on src/reconcile.js
>    if (typeof element.type === "string") {
А чем, кстати, этот `if` отличается от предыдущего?

2020-04-16 15:17 UTC, oceandrama commented on src/updateDomProperties.js
> +  if (JSON.stringify(prevProps) === JSON.stringify(nextProps)) {
Такое сравнение может учесть только сериализуемые значения. Например, функции так не проверить

2020-04-16 19:55 UTC, actimeller commented on src/reconcile.js
>    if (typeof element.type === "string") {
Я не понимаю, а каком if'e речь. Интерфейс гитхаба не даёт понять.

2020-04-16 19:55 UTC, actimeller commented on src/updateDomProperties.js
> +  if (JSON.stringify(prevProps) === JSON.stringify(nextProps)) {
Какое сравнение использовать?

2020-04-16 19:56 UTC, actimeller commented on src/reconcile.js
> +    !element.type.isClass
После предыдущих правок в мой код тесты срабатывают, но в браузере рендер не работает. Поэтому я добавлял if’ы и т.п.

2020-04-16 19:57 UTC, actimeller commented on src/reconcile.js
>    if (typeof element.type === "string") {
Уточни, пожалуйста, о каких строках речь?

2020-04-17 11:29 UTC, oceandrama commented on src/reconcile.js
>    if (typeof element.type === "string") {
Ну вот, на 19 строке. Бегло посмотрел, кажется, что в теле выполняются одни и те же действия

2020-04-17 11:35 UTC, actimeller commented on src/reconcile.js
>    if (typeof element.type === "string") {
Сначала я проверил, что instance.element.type впринципе существует, а потом сравнил его

2020-04-17 11:40 UTC, oceandrama commented on src/updateDomProperties.js
> +  if (JSON.stringify(prevProps) === JSON.stringify(nextProps)) {
По-честному брать поля и сравнивать. Давай `shallowEqual` реализуем для начала

2020-04-17 11:45 UTC, oceandrama commented on src/reconcile.js
>    if (typeof element.type === "string") {
Что условия отличаются это понятно, но действия, кажется, совпадают
```
19: if (...) {
    updateDomProperties(instance.dom, instance.element.props, element.props);	    
    instance.childInstances = reconcileChildren(instance, element);
    instance.element = element;
    return instance;
  }
```
```
36: if (typeof element.type === "string") {
    updateDomProperties(instance.dom, instance.element.props, element.props);
    instance.childInstances = reconcileChildren(instance, element);
    instance.element = element;
    return instance;
 }
```

2020-05-04 13:42 UTC, oceandrama requested changes

2020-05-04 13:42 UTC, oceandrama commented on utils/shallowEqual.js
> +const shallowEqual = (objA, objB) => {
Эта функция теперь нигде не используется?

2020-05-04 13:42 UTC, oceandrama commented on src/updateDomProperties.js
> +      if (prevProps[name] !== nextProps[name]) {
Тесты, тесты, тесты
Попробуй сначала установить элементу `{ top: 10 }`, а потом `{ bottom: 10 }`, например. Какой итоговый набор пропсов мы ожидаем?

2020-05-05 12:25 UTC, actimeller commented on src/updateDomProperties.js
> +      if (prevProps[name] !== nextProps[name]) {
Полагаю, что итоговый набор пропсов должен быть { bottom: 10 }
Исправил

2020-05-05 12:26 UTC, actimeller commented on utils/shallowEqual.js
> +const shallowEqual = (objA, objB) => {
Теперь используется

2020-05-07 17:39 UTC, merged